[package]
name = "shoview"
version = "0.1.0"
authors = ["aol1306 <jdzieciatko@gmail.com>"]
edition = "2018"

[dependencies]
mongodb = "0.3.12"
simplelog = "*"
log = "*"
argparse = "*"
url = "*"
tera = "*"
serde_json = "*"
